name: flutter_bootstrap
description: A partial implementation of Bootstrap Grid system in Flutter for Responsive Layout.
version: 2.0.0
homepage: https://github.com/boeledi/flutter_bootstrap

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
